# Generated by Django 2.2.1 on 2019-06-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('record_name', models.CharField(max_length=400)),
                ('genre', models.CharField(max_length=200)),
                ('contributor', models.CharField(max_length=400)),
                ('label', models.CharField(max_length=400)),
                ('logo', models.CharField(max_length=1000)),
                ('record_format', models.CharField(max_length=200)),
            ],
        ),
    ]
