# Generated by Django 2.2.1 on 2019-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
