# Generated by Django 2.2.1 on 2019-06-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordcollection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
